name: runner_x
os: windows
arch: x64

language: powershell
image_source: local
payload: shellcode
algorithm: LSB-X

params:
  MAX_BITS: 2208
  PAYLOAD_SOURCE: "./samples/shellcode/shellcode_x64_lsbx.bmp"
  LSBX_CHANNEL: R
