name: runner_m
os: windows
arch: x64

language: powershell
delivery_method: local
payload_type: shellcode
algorithm: LSBM

params:
  MAX_BITS: 2208
  PAYLOAD_SOURCE: "./samples/shellcode/shellcode_x64_lsbm.bmp"
