name: runner_x
os: windows
arch: x64

language: powershell
delivery_method: local
payload_type: shellcode
algorithm: LSB-X

params:
  MAX_BITS: 2208
  PAYLOAD_SOURCE: "./samples/shellcode/shellcode_x64.bmp"
  LSBX_CHANNEL: R
