name: runner
os: windows
arch: x64

language: powershell
image_source: image_file
payload: shellcode
algorithm: LSB

params:
  MAX_BITS: 2208
  PAYLOAD_SOURCE: "./samples/shellcode/shellcode_x64.bmp"
