name: runner_m
os: windows
arch: x64

language: powershell
image_source: image_file
payload: shellcode
algorithm: LSBM

params:
  BYTE_LENGTH: 276
  IMAGE_SOURCE: "./samples/shellcode/shellcode_x64_lsbm.bmp"
