name: runner
os: windows
arch: x64

language: powershell
image_source: image_file
payload: shellcode
algorithm: LSB

params:
  BYTE_LENGTH: 276
  IMAGE_SOURCE: "./samples/shellcode/shellcode_x64.bmp"
